export function container2(data){
    const secondaryNav = document.createElement('div')
    secondaryNav.classList.add("secondary-nav")
    const Navsticky = document.createElement('nav')
    Navsticky.classList.add("container","d-flex")
    Navsticky.id="sticky-nav"
    const dropDown = document.createElement('div')
    dropDown.classList.add('dropdown')
    const buttonGroup = document.createElement('div')
    buttonGroup.classList.add('button-group')
    const btnA = document.createElement('a')
    btnA.classList.add('btn-3','btn--md')
    const btnText = document.createElement('span')
    btnText.classList.add('btn-text')
    btnA.appendChild(btnText)
    btnText.textContent=data.navigation.navbtn
    buttonGroup.appendChild(btnA)
    const dropdownMenu = document.createElement('div')
    dropdownMenu.classList.add('dropdown-menu','menu-list')
    const ocrSlider = document.createElement('div')
    ocrSlider.classList.add('col','ocr-slider')
    const sliderOverflow= document.createElement('div')
    sliderOverflow.classList.add('slider__overflow')
    const sliderWindow = document.createElement('ul')
    sliderWindow.classList.add('slider__window')
    sliderOverflow.appendChild(sliderWindow)
    ocrSlider.appendChild(sliderOverflow)
    dropdownMenu.appendChild(ocrSlider)
    dropDown.appendChild(dropdownMenu)
    Navsticky.appendChild(dropDown)
    secondaryNav.appendChild(Navsticky)
    Navsticky.appendChild(buttonGroup)
    document.getElementById('sticky').appendChild(secondaryNav)
    data.navigation.nav.forEach((item,idx)=>{
        const menuList = document.createElement('li')
        menuList.classList.add('menu-list__list-item')
        const itemlink = document.createElement('a')
        itemlink.classList.add('menu-list__item-link')
        const indicator = document.createElement('div')
        indicator.classList.add('indicator','indicator--shape-pill')
        itemlink.appendChild(indicator)
        const menulistSpan = document.createElement('span')
        menulistSpan.classList.add('menu-list__list-item-text')
        const tokenText = document.createElement('div')
        tokenText.classList.add('token-text')
        //console.log(tokenText)
        tokenText.textContent=item
        menulistSpan.appendChild(tokenText)
        itemlink.appendChild(menulistSpan)
        menuList.appendChild(itemlink)
        //console.log(menuList)
        sliderWindow.appendChild(menuList)
        menuList.addEventListener('click',()=>{
            //console.log('clicked',item)
            document.querySelectorAll('.indicator').forEach(indicator=>{
                indicator.classList.remove('active')
                //console.log(indicator)
            })
            const indicator=menuList.querySelector('.indicator')
            indicator.classList.add('active')
        })  
    })
}