export function container6(data){
    const mediaAsset = document.createElement('div')
    mediaAsset.classList.add('ocr-img','media__asset')
    const picture = document.createElement('picture')
    const backgroundImage = document.createElement('img')
    backgroundImage.src= data.gartner.backgroundImage
    document.getElementById('background').appendChild(mediaAsset)
    mediaAsset.appendChild(picture)
    picture.appendChild(backgroundImage)

    const colEl = document.createElement('div')
    colEl.classList.add('col')
    const cardHorizontal = document.createElement('div')
    cardHorizontal.classList.add('card-horizontal-container')
    const rowEl = document.createElement('div')
    rowEl.classList.add('row')
    const col2El = document.createElement('div')
    col2El.classList.add('col')
    const cardHOri= document.createElement('div')
    cardHOri.classList.add('card-horizontal')
    const row2El = document.createElement('div')
    row2El.classList.add('row')
    document.getElementById('slot-4').appendChild(colEl)
    colEl.appendChild(cardHorizontal)
    cardHorizontal.appendChild(rowEl)
    rowEl.appendChild(col2El)
    col2El.appendChild(cardHOri)
    cardHOri.appendChild(row2El)

    const mediaHori = document.createElement('div')
    mediaHori.classList.add('card-horizontal__media','col-lg-12','col-md-6')
    const media = document.createElement('div')
    media.classList.add('media','media--ratio-4-3')
    const imgOcr = document.createElement('div')
    imgOcr.classList.add('ocr-img','media__asset')
    const image = document.createElement('img')
    image.src= data.gartner.gartnerImage
    mediaHori.appendChild(media)
    media.appendChild(imgOcr)
    imgOcr.appendChild(image)
    row2El.appendChild(mediaHori)

    const contentHori = document.createElement('div')
    contentHori.classList.add('card-horizontal__content','col-lg-12','col-md-6')
    const blockFeature = document.createElement('div')
    blockFeature.classList.add('block-feature','d-flex','align-items-start')
    const topFeature = document.createElement('div')
    topFeature.classList.add('block-feature__top','d-flex','flex-row')
    const headingFeature = document.createElement('div')
    headingFeature.classList.add('block-feature__heading','d-flex','flex-column')
    const titleFeature = document.createElement('div')
    titleFeature.classList.add('block-feature__title')
    const div = document.createElement('div')
    const h2 = document.createElement('h2')
    const span = document.createElement('span')
    span.classList.add('d-block','h3')
    span.textContent=data.gartner.dBlockHead
    h2.appendChild(span)
    div.appendChild(h2)
    titleFeature.appendChild(div)
    headingFeature.appendChild(titleFeature)
    topFeature.appendChild(headingFeature)
    blockFeature.appendChild(topFeature)
    contentHori.appendChild(blockFeature)
    row2El.appendChild(contentHori)

    const bodyFeature = document.createElement('div')
    bodyFeature.classList.add('block-feature__body','d-flex','flex-column')
    const base = document.createElement('div')
    base.classList.add('base','block-feature__paragraph')
    const divs = document.createElement('div')
    divs.textContent= data.gartner.para
    base.appendChild(divs)
    bodyFeature.appendChild(base)
    blockFeature.appendChild(bodyFeature)

    const blockSilm = document.createElement('div')
    blockSilm.classList.add('block-slim')
    const actionD = document.createElement('div')
    actionD.classList.add('action','d-contents')
    const btn = document.createElement('div')
    btn.classList.add('btn','btn--md')
    const spanEl = document.createElement('span')
    spanEl.classList.add('btn__text')
    spanEl.textContent=data.gartner.btn
    btn.appendChild(spanEl)
    actionD.appendChild(btn)
    blockSilm.appendChild(actionD)
    contentHori.appendChild(blockSilm)
}