export function container10(data){
    const ocrImage = document.createElement('div')
    ocrImage.classList.add('ocr-img','media__asset')
    const picture = document.createElement('picture')
    const backgrounnd  =document.createElement('img')
    backgrounnd.src = data.nextstep.image
    document.getElementById('image_master').appendChild(ocrImage)
    ocrImage.appendChild(picture)
    picture.appendChild(backgrounnd)
    console.log(ocrImage)

    const colEl = document.createElement('div')
    colEl.classList.add('col')
    const lay = document.createElement('div')
    lay.classList.add('layout','section-master__layout','align-center')
    const collay = document.createElement('div')
    collay.classList.add('layout__col')
    const layhead =document.createElement('div')
    layhead.classList.add('section-master__layout-header')
    const headBlock = document.createElement('div')
    headBlock.classList.add('block-heading')
    const titleBLock = document.createElement('div')
    titleBLock.classList.add('block-heading__title')
    const idv = document.createElement('div')
    const h23 = document.createElement('h2')
    h23.textContent=data.nextstep.head

    document.getElementById('row-5').appendChild(colEl)
    colEl.appendChild(lay)
    lay.appendChild(collay)
    collay.appendChild(layhead)
    layhead.appendChild(headBlock)
    headBlock.appendChild(titleBLock)
    titleBLock.appendChild(idv)
    idv.appendChild(h23)
    //console.log(colEl)

    const col2El =document.createElement('div')
    col2El.classList.add('col')
    const threecard = document.createElement('div')
    threecard.classList.add('three-up-cards','layout','layout--col-3')
    document.getElementById('slot-6').appendChild(col2El)
    col2El.appendChild(threecard)
    data.nextstep.threecard.forEach((item,idx)=>{
        const singlecard = document.createElement('div')
        singlecard.classList.add('three-up-cards__card','layout__col')
        threecard.appendChild(singlecard)
        const card = document.createElement('div')
        card.classList.add('card')
        const cardcontent  = document.createElement('div')
        cardcontent.classList.add('card__content')

        const blockFeature = document.createElement('div')
        blockFeature.classList.add('block-feature','d-flex')
        const bodyFeature = document.createElement('div')
        bodyFeature.classList.add('block-feature__body','d-flex','flex-column','gap')

        const headingFeature = document.createElement('div')
        headingFeature.classList.add('block-feature__headings','d-flex','flex-column')
        bodyFeature.appendChild(headingFeature)
        const titlefea = document.createElement('div')
        titlefea.classList.add('block-feature__title')
        const div3 = document.createElement('div')
        const h3 = document.createElement('h3')
        const dspan = document.createElement('span')
        dspan.classList.add('d-block','h5')
        dspan.textContent = item.head
        singlecard.appendChild(card)
        card.appendChild(cardcontent)
        cardcontent.appendChild(blockFeature)
        blockFeature.appendChild(bodyFeature)
        bodyFeature.appendChild(headingFeature)
        headingFeature.appendChild(titlefea)
        titlefea.appendChild(div3)
        div3.appendChild(h3)
        h3.appendChild(dspan)
        
        
        const bsefeature = document.createElement('div')
        bsefeature.classList.add('base','block-feature__paragraph')
        bodyFeature.appendChild(bsefeature)
        const div4 = document.createElement('div')
        div4.textContent = item.para
        bsefeature.appendChild(div4)

        const blockSlim = document.createElement('div')
        blockSlim.classList.add('block-slim')
        cardcontent.appendChild(blockSlim)
        const Actiond = document.createElement('div')
        Actiond.classList.add('action','d-contents')
        const link = document.createElement('div')
        link.classList.add('link')
        const btn = document.createElement('div')
        btn.classList.add('btn','btn--icon-only','btn--sm')
        const glphy = document.createElement('span')
        glphy.classList.add('glph-prepend')
        blockSlim.appendChild(Actiond)
        Actiond.appendChild(link)
        link.appendChild(btn)
        btn.appendChild(glphy)

        const linktext = document.createElement('div')
        linktext.classList.add('link__text')
        linktext.textContent = item.btn
        link.appendChild(linktext)


    })
    //console.log(threecard)

}